# Generated by Django 2.1.5 on 2019-01-16 19:02

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('report_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=10240)),
                ('image', stdimage.models.StdImageField(blank=True, upload_to='')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.Report')),
            ],
        ),
    ]
